### ISSUE TITLE
1.10.4 breaks with Magento 1.9 due to Varien Autoloader

### ISSUE THREAD

**Issue by andyt** [colinmollenhour/Cm_Cache_Backend_Redis#132]
With 1.9.3.8 (and probably others).

The stack trace makes it clear that the class_exists call is triggering the Autoloader, which fails.

PHP 7.1.17.

```
Warning: include(Credis/Cluster.php): failed to open stream: No such file or directory  in /var/www/htdocs/lib/Varien/Autoload.php on line 94

#0 /var/www/htdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(Credis/...', '/var/www/htdocs...', 94, Array)
#1 /var/www/htdocs/lib/Varien/Autoload.php(94): include()
#2 [internal function]: Varien_Autoload->autoload('Credis_Cluster')
#3 [internal function]: spl_autoload_call('Credis_Cluster')
#4 /var/www/htdocs/app/code/community/Cm/Cache/Backend/Redis.php(235): class_exists('Credis_Cluster')
#5 /var/www/htdocs/lib/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct(Array)
#6 /var/www/htdocs/lib/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)
#7 /var/www/htdocs/app/code/core/Mage/Core/Model/Cache.php(136): Zend_Cache::factory('Varien_Cache_Co...', 'Cm_Cache_Backen...', Array, Array, true, true, true)
#8 /var/www/htdocs/app/code/core/Mage/Core/Model/Config.php(1357): Mage_Core_Model_Cache->__construct(Array)
#9 /var/www/htdocs/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('core/cache', Array)
#10 /var/www/htdocs/app/code/core/Mage/Core/Model/App.php(412): Mage::getModel('core/cache', Array)
#11 /var/www/htdocs/app/code/core/Mage/Core/Model/App.php(306): Mage_Core_Model_App->_initCache(Array)
#12 /var/www/htdocs/app/code/core/Mage/Core/Model/App.php(348): Mage_Core_Model_App->baseInit(Array)
#13 /var/www/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#14 /var/www/htdocs/index.php(83): Mage::run('freeborn', 'store')
#15 {main}
```

**Comment by colinmollenhour** [comment]
Thanks, Andy. I just pushed a fix and will tag a new release.
