### ISSUE TITLE
Error cleaning cache by mode matchingAnyTag

### ISSUE THREAD

**Issue by norgeindian** [colinmollenhour/Cm_Cache_Backend_Redis#164]
Since we updated to the newest version of this module, we get the following error every time when flushing the cache:

`Error cleaning cache by mode matchingAnyTag: A pipeline is already in use and only one pipeline is supported`

Any ideas what might go wrong here?

**Comment by colinmollenhour** [comment]
No idea, can you provide a backtrace?

What was the version you were previously using?

@nemphys have you experienced this before?

**Comment by nemphys** [comment]
No idea either, I have been running the latest fix in production since the day it was merged and have not seen any logged errors.

**Comment by norgeindian** [comment]
This is the call stack:

```a:5:{i:0;s:109:"Error cleaning cache by mode matchingAnyTag: A pipeline is already in use and only one pipeline is supported.";i:1;s:2324:"#0 /var/www/share/www.shop-url.de/live/.modman/Cm_CacheBackendRedis/Cm/Ca$
#1 /var/www/share/www.shop-url.de/live/shop/lib/Zend/Cache/Core.php(465): Cm_Cache_Backend_Redis->clean('matchingAnyTag', Array)
#2 /var/www/share/www.shop-url.de/live/shop/lib/Varien/Cache/Core.php(211): Zend_Cache_Core->clean('matchingAnyTag', Array)
#3 /var/www/share/www.shop-url.de/live/.modman/Lesti_Fpc/app/code/community/Lesti/Fpc/Model/Fpc.php(149): Varien_Cache_Core->clean('matchingAnyTag', Array)
#4 /var/www/share/www.shop-url.de/live/.modman/Lesti_Fpc/app/code/community/Lesti/Fpc/Model/Observer/Clean.php(28): Lesti_Fpc_Model_Fpc->clean()
#5 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Model/App.php(1374): Lesti_Fpc_Model_Observer_Clean->adminhtmlCacheFlushAll(Object(Varien_Event_Observer))
#6 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Model/App.php(1353): Mage_Core_Model_App->_callObserverMethod(Object(Lesti_Fpc_Model_Observer_Clean), 'adminhtmlCacheF...', Object(Varien_Event_$
#7 /var/www/share/www.shop-url.de/live/shop/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('adminhtml_cache...', Array)
#8 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Adminhtml/controllers/CacheController.php(56): Mage::dispatchEvent('adminhtml_cache...')
#9 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CacheController->flushAllAction()
#10 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('flushAll')
#11 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/share/www.shop-url.de/live/shop/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/share/www.shop-url.de/live/shop/app/Mage.php(686): Mage_Core_Model_App->run(Array)
#14 /var/www/share/www.shop-url.de/live/shop/index.php(83): Mage::run('', 'store')
#15 {main}";s:3:"url";s:70:"/index.php/admin/cache/flushAll/key/d70f3660b0ee7acd5c282a39f0ad0330/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```
Last time we updated was December 2018, so I assume version 1.10.6. And like I wrote, there everything worked fine.
Might it be that I have to adapt the config somehow since then?
Interestingly no errors happen when I run `cache:clean`, only when running `cache:flush`.
Do you have any idea what I could check?

**Comment by colinmollenhour** [comment]
Your stack trace is missing the first frame..

Do you have lua mode enabled or no?

**Comment by norgeindian** [comment]
@colinmollenhour , sorry, here is the first line:
```
a:5:{i:0;s:109:"Error cleaning cache by mode matchingAnyTag: A pipeline is already in use and only one pipeline is supported.";i:1;s:2324:"#0 /var/www/share/www.shop-url.de/live/.modman/Cm_CacheBackendRedis/Cm/Cache/Backend/Redis.php(999): Zend_Cache::throwException('Error cleaning ...', Object(CredisException))
```
Any idea?

**Comment by colinmollenhour** [comment]
Still not really any idea. But what about lua mode, are you using it? Have you tried it both ways?

**Comment by norgeindian** [comment]
@colinmollenhour , tried both ways, still the same error.
Strange.... I will try to debug this further and will let you know as soon as I found out what is going wrong here.

**Comment by mlaurense** [comment]
I experienced the same, although setting use_lua to 1 seemed to have fixed this. I will keep a close watch to see if this issue returns.

**Comment by snufpunk** [comment]
We had the same issue, does not recurr after setting use_lua to 1.

**Comment by ioweb-gr** [comment]
I had the same issue 

```
a:5:{i:0;s:64:"A pipeline is already in use and only one pipeline is supported.";i:1;s:2960:"#0 /public_html/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(626): Credis_Client->__call('pipeline', Array)
#1 /public_html/lib/Zend/Cache/Core.php(390): Cm_Cache_Backend_Redis->save('a:4:{s:2:"id";a...', '4af_DB_PDO_MYSQ...', Array, false)
#2 /public_html/lib/Varien/Cache/Core.php(145): Zend_Cache_Core->save('a:4:{s:2:"id";a...', '4af_DB_PDO_MYSQ...', Array, false, 8)
#3 /public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(1593): Varien_Cache_Core->save('a:4:{s:2:"id";a...', 'DB_PDO_MYSQL_DD...', Array)
#4 /public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(1723): Varien_Db_Adapter_Pdo_Mysql->saveDdlCache('plumbase_produc...', 1, 'a:4:{s:2:"id";a...')
#5 /public_html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(402): Varien_Db_Adapter_Pdo_Mysql->describeTable('plumbase_produc...')
#6 /public_html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(378): Mage_Core_Model_Resource_Db_Abstract->_getLoadSelect('signature', '095a1b43effec73...', Object(Plumrocket_Base_Model_Product))
#7 /public_html/app/code/core/Mage/Core/Model/Abstract.php(237): Mage_Core_Model_Resource_Db_Abstract->load(Object(Plumrocket_Base_Model_Product), '095a1b43effec73...', 'signature')
#8 /public_html/app/code/community/Plumrocket/Base/Model/Product.php(22): Mage_Core_Model_Abstract->load('095a1b43effec73...', 'signature')
#9 /public_html/app/code/community/Plumrocket/Base/Model/Product.php(22): Plumrocket_Base_Model_Product->load('Base')
#10 /public_html/app/code/core/Mage/Core/Model/App.php(1410): Plumrocket_Base_Model_Product->reindex(Object(Varien_Event_Observer))
#11 /public_html/app/code/core/Mage/Core/Model/App.php(1389): Mage_Core_Model_App->_callObserverMethod(Object(Plumrocket_Base_Model_Product), 'reindex', Object(Varien_Event_Observer))
#12 /public_html/app/Mage.php(502): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#13 /public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(571): Mage::dispatchEvent('controller_acti...', Array)
#14 /public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(441): Mage_Core_Controller_Varien_Action->postDispatch()
#15 /public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('save')
#16 /public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#18 /public_html/app/Mage.php(737): Mage_Core_Model_App->run(Array)
#19 /public_html/index.php(83): Mage::run('', 'store')
```

I'm going to try use_lua as well and report back

**Comment by colinmollenhour** [comment]
I don't think there is even a good reason to not remove the non-lua mode, since the version of Redis that didn't support it is long gone..

**Comment by luigifab** [comment]
Since I have updated to OpenMage 20.1.0-rc1 (colinmollenhour/cache-backend-redis 1.16 installed by composer), I have, **rarely**, the same error (`Error cleaning cache by mode matchingAnyTag: A pipeline is already in use and only one pipeline is supported`) when we try to flush cache with left button of OM backend:

![image](https://user-images.githubusercontent.com/31816829/224038500-3b8db199-d607-4630-9cdc-034aaa9f398b.png)
left button: `flushSystem`
right button: `flushAll`

```php
    public function flushSystemAction()
    {
        Mage::app()->cleanCache();
        Mage::dispatchEvent('adminhtml_cache_flush_system');
        $this->_getSession()->addSuccess(Mage::helper('adminhtml')->__("The OpenMage cache ..."));
        $this->_redirect('*/*');
    }
```

The Sentry stack trace:
![image](https://user-images.githubusercontent.com/31816829/224037108-48c3a088-6455-4ecd-b5c4-a8f3a685e357.png)

We are using Redis server v=5.0.3.
This bug started when I updated OM.
Last time, I tried to flush cache with right button, then left button, and it temporary fix the problem.
But...

I found that: https://magento.stackexchange.com/a/95386/101197
But not sure how to think.

**Comment by colinmollenhour** [comment]
Probably there is a different error being thrown and the pipeline management is not resetting the pipeline or something along those lines.. Using LUA mode makes it really simple from teh PHP side though which is why this fixes it in most cases.. Just to confirm, do you have LUA mode enabled?

**Comment by luigifab** [comment]
If it's `<use_lua>0</use_lua>`, so no disabled.

**Comment by luigifab** [comment]
I updated to Redis 6.0.16, same, but still rarely.

**Comment by luigifab** [comment]
Fixed with `<use_lua>1</use_lua>`.

**Comment by fballiano** [comment]
I found this issue because I'm also facing this same problem on redis 5.0.7, seems to be fixed enabling `lua` on all 3 redis connections (openmage cache, openmage full page cache, sessions).

**Comment by amenk** [comment]
Just for the record:

We ran into the same error message after an Magento upgrade.

  - Magento: 2.4.7-p10 → 2.4.8-p5                                                                                                                                                                                                                                                                                                                                                                                                 
  - PHP: 8.3 → 8.4                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                  
The Redis libraries were unchanged in that upgrade. The bump that introduced the buggy GC code came earlier, in the 2.4.7-p9 patch upgrade  colinmollenhour/cache-backend-redis 1.17.1 → 1.18.0 (and credis 1.17.0 → 1.17.1).

But the bug surfaced only recently. It might have been related to the fact that we by mistake changed the Cache class to `Magento\\Framework\\Cache\\Backend\\Valkey` temporarily because Magento documented it's available in 2.4.8 (which it isn't). Then we changed back and it still did not work (the error appeared in the pacemaker import module)

Important: We did not use the php8.4-redis PHP module before (we also did not use it in php8.3) - but the good news is, that **`apt install php-redis` fixed the issue** for us.

Here is some more theory from Claude Fable:

>   It's a state-machine mismatch between the cache backend and Credis's standalone driver, introduced by the GC rewrite in cache-backend-redis 1.18.0:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>  1. Credis standalone mode has fragile pipeline state. Credis_Client tracks an open pipeline with a boolean (usePipeline). Calling pipeline() while one is open throws "A pipeline is already in use..." (Client.php:1120). The flags are only reset inside exec()/discard(). The phpredis driver branch doesn't have this trap — nested pipeline()/multi() is simply a no-op there (Client.php:1329-1334).                      
>  2. The backend can abandon a pipeline mid-flight. If any exception escapes between pipeline() and exec(), the client object is permanently stuck with usePipeline = true. The backend's own clean() catch (Redis.php:1140) rethrows without calling discard(), and nothing else ever resets the flag. In a long-running process (a Pacemaker consumer, a queue worker, anything that survives exceptions) every later cache     
  operation that opens a pipeline then throws forever — which is exactly what abandoned your indexer pipeline.                                                                                                                                                                                                                                                                                                                    
>  3. 1.18.0 reintroduced the exposure. This error class has a long history (issue #164); the maintainer's resolution in 1.17.0 was "make Lua mode the default so PHP-side pipelines mostly disappear" — explicitly not fixing the standalone driver ("I'm not really interested in fixing the non-lua mode"). Then 1.18.0's new _collectGarbageIterative() added fresh raw-pipeline code that runs even in Lua mode, including    
  throw-capable statements inside open pipelines (e.g. $pipelineResults[$index] at Redis.php:1005, which Magento's error handler turns from a warning into an exception if a result is missing).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
> So "needs phpredis" isn't an official requirement — it's that the pure-PHP fallback driver's pipeline handling is effectively unmaintained, and only the phpredis driver is robust against this. The clean upstream fix would be either resetting pipeline state on exception (a discard() in a finally/catch around every pipeline block), or making standalone pipeline() nesting a no-op like the phpredis branch.
