### ISSUE TITLE
PHP Fatal error: Uncaught exception 'CredisException' with message 'Lost connection to Redis server

### ISSUE THREAD

**Issue by RonnyWo** [colinmollenhour/Cm_Cache_Backend_Redis#80]
Since a few days i get very often the following error

apache2: PHP Fatal error:  Uncaught exception 'CredisException' with message 'Lost connection to Redis server.' in /pathtomagento/lib/Credis/Client.php:693#012Stack trace:#012#0 /pathtomagento/lib/Credis/Client.php(538): Credis_Client->read_reply('select')#012#1 /pathtomagento/lib/Credis/Client.php(440): Credis_Client->__call('select', Array)#012#2 /pathtomagento/app/code/community/Cm/Cache/Backend/Redis.php(135): Credis_Client->select(0)#012#3 /pathtomagento/lib/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct(Array)#012#4 /pathtomagento/lib/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true)#012#5 /pathtomagento/app/code/local/NBSSystem/Nitrogento/Model/Core/Cache.php(28): Zend_Cache::factory('Varien_Cache_Co...', 'Cm_Cache_Backen...', Array, Array, tr in /pathtomagento/lib/Credis/Client.php on line 693

This error will make my server crash, because all clients from apache are being used.

This is on Magento 1.8.1 CE. Apache 2.2.22, PHP 5.3.10-1ubuntu3.15, redis-cli 2.2.12
Does anyone know what is wrong?

**Comment by vkalchenko** [comment]
Hello @colinmollenhour 

I think I can provide more examples with sUnion-related errors. This sometimes happens on production for EE clients and large FPC.

Here's error with trace:
```
2015-12-29T05:00:01+00:00 DEBUG (7): exception 'RedisException' with message 'read error on connection' in /data/www/html/mywebsite.com/lib/Credis/Client.php:1044
Stack trace:
#0 [internal function]: Redis->sUnion('zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...', 'zc:ti:e85_CATAL...')
#1 /data/www/html/mywebsite.com/lib/Credis/Client.php(1044): call_user_func_array(Array, Array)
#2 /data/www/html/mywebsite.com/app/code/community/Cm/Cache/Backend/Redis.php(780): Credis_Client->__call('sUnion', Array)
#3 /data/www/html/mywebsite.com/app/code/community/Cm/Cache/Backend/Redis.php(780): Credis_Client->sUnion(Array)
#4 /data/www/html/mywebsite.com/app/code/community/Cm/Cache/Backend/Redis.php(472): Cm_Cache_Backend_Redis->getIdsMatchingAnyTags(Array)
#5 /data/www/html/mywebsite.com/app/code/community/Cm/Cache/Backend/Redis.php(664): Cm_Cache_Backend_Redis->_removeByMatchingAnyTags(Array)
#6 /data/www/html/mywebsite.com/lib/Zend/Cache/Core.php(461): Cm_Cache_Backend_Redis->clean('matchingAnyTag', Array)
#7 /data/www/html/mywebsite.com/lib/Varien/Cache/Core.php(211): Zend_Cache_Core->clean('matchingAnyTag', Array)
#8 /data/www/html/mywebsite.com/app/code/core/Mage/Core/Model/Cache.php(455): Varien_Cache_Core->clean('matchingAnyTag', Array)
#9 /data/www/html/mywebsite.com/app/code/core/Enterprise/PageCache/Model/Observer/Index.php(50): Mage_Core_Model_Cache->clean(Array)
#10 /data/www/html/mywebsite.com/app/code/core/Enterprise/PageCache/Model/Observer/Index.php(73): Enterprise_PageCache_Model_Observer_Index->_cleanEntityCache(Object(Mage_Catalog_Model_Product), Array)
#11 /data/www/html/mywebsite.com/app/code/core/Mage/Core/Model/App.php(1351): Enterprise_PageCache_Model_Observer_Index->cleanProductsCacheAfterPartialReindex(Object(Varien_Event_Observer))
#12 /data/www/html/mywebsite.com/app/code/core/Mage/Core/Model/App.php(1330): Mage_Core_Model_App->_callObserverMethod(Object(Enterprise_PageCache_Model_Observer_Index), 'cleanProductsCa...', Object(Varien_Event_Observer))
#13 /data/www/html/mywebsite.com/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('cataloginventor...', Array)
#14 /data/www/html/mywebsite.com/app/code/core/Enterprise/CatalogInventory/Model/Index/Action/Refresh/Changelog.php(96): Mage::dispatchEvent('cataloginventor...', Array)
#15 /data/www/html/mywebsite.com/app/code/core/Enterprise/CatalogInventory/Model/Index/Action/Refresh/Changelog.php(49): Enterprise_CatalogInventory_Model_Index_Action_Refresh_Changelog->_reindex(Array)
#16 /data/www/html/mywebsite.com/app/code/core/Enterprise/Mview/Model/Client.php(109): Enterprise_CatalogInventory_Model_Index_Action_Refresh_Changelog->execute()
#17 /data/www/html/mywebsite.com/app/code/core/Enterprise/Index/Model/Observer.php(129): Enterprise_Mview_Model_Client->execute('enterprise_cata...')
#18 [internal function]: Enterprise_Index_Model_Observer->refreshIndex(Object(Mage_Cron_Model_Schedule))
#19 /data/www/html/mywebsite.com/app/code/core/Mage/Cron/Model/Observer.php(325): call_user_func_array(Array, Array)
#20 /data/www/html/mywebsite.com/app/code/core/Mage/Cron/Model/Observer.php(262): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element), true)
#21 /data/www/html/mywebsite.com/app/code/core/Mage/Cron/Model/Observer.php(89): Mage_Cron_Model_Observer->_processAlwaysTask('enterprise_refr...', Object(Mage_Core_Model_Config_Element))
#22 /data/www/html/mywebsite.com/app/code/core/Mage/Core/Model/App.php(1351): Mage_Cron_Model_Observer->dispatchAlways(Object(Varien_Event_Observer))
#23 /data/www/html/mywebsite.com/app/code/core/Mage/Core/Model/App.php(1330): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatchAlways', Object(Varien_Event_Observer))
#24 /data/www/html/mywebsite.com/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('always', Array)
#25 /data/www/html/mywebsite.com/cron.php(77): Mage::dispatchEvent('always')
#26 {main}
```

Looks like it might be related to sufficient big sUnion query and Redis just unable to handle so big request.

**Comment by colinmollenhour** [comment]
@vkalchenko It appears you are not using the LUA mode. I would think the LUA mode would perform better, have you tried it?

Either way, try lowering sunion_chunk_size.

**Comment by vkalchenko** [comment]
Thank you @colinmollenhour. No, we did not try LUA. I will let you know if it helps.
